### ISSUE TITLE
it.unich.scalafix#scalafix_2.12;0.7.0-SNAPSHOT: not found

### ISSUE THREAD

**Issue by herrBez** [jandom-devel/Jandom#13]
[2017-11-13]
If you clone and try to compile the project with sbt you'll get the following exception:

```sbt.librarymanagement.ResolveException: unresolved dependency: it.unich.scalafix#scalafix_2.12;0.7.0-SNAPSHOT: not found```

If you look the logs you can see that it searches the library: [on this maven repository url](https://repo1.maven.org/maven2/it/unich/scalafix/scalafix_2.11/), where the searched version of scala-fix is not present.

**QUICK WORKAROUND**
I managed to solve this issue by simply downloading, compiling scala-fix (generate the .jar file) and including it in the sbt project (```  "it.unich.scalafix" %% "scalafix" % "0.7.0-SNAPSHOT" from file:///local/path/scala-fix.jar```), but I think it would be better if it would be automatic.

**SOLUTIONS**
- The simplest solution would be to upload the latest scala-fix library version on the [on this maven repository url](https://repo1.maven.org/maven2/it/unich/scalafix/scalafix_2.11/). 
- Otherwise you can also consider to use ["github submodules"](https://github.com/blog/2104-working-with-submodules) (I tried this approach and it worked for me):
```git submodule add https://github.com/jandom-devel/ScalaFix scala-fix```
and then add this lines to the build.sbt file in the root directory:
```lazy val ScalaFix = project in file("scala-fix")```
```lazy val JandomCore = project in file("core") enablePlugins(BuildInfoPlugin) dependsOn ScalaFix```

**Comment by amato-gianluca** [comment]
Thanks for the report. ScalaFix 0.7.0-SNAPSHOT is now published in the Sonatype Snapshots repository. We will evaluate whether to use github submodules.
